import Head from 'next/head'
import styles from '@/styles/Home.module.css'
function Home({ aboutData }) {
  const { title, slogan } = aboutData;
  console.log(aboutData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{title}</p>
        <p>{slogan}</p>
      </main>
    </>
  )
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://strapi-production-ca04.up.railway.app/api/about')
  const about = await res.json();
  const aboutData = about.data.attributes;

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      aboutData,
    },
    revalidate: 10,
  }
}

export default Home;
